version: '3'

services:

  prometheus:
    image: "prom/prometheus:latest"
    hostname: "prometheus"
    restart: always
    networks:
    - website_monitoring
    ports:
    - "127.0.0.1:9090:9090"
    user: root
    volumes:
    - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    - "./config/prometheus/targets.yml:/etc/prometheus/targets.yml:ro"
    - "./config/prometheus/rules:/etc/prometheus/rules"
    - "prometheus_data:/prometheus"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--storage.tsdb.retention.time=30d"
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    - '--web.enable-admin-api'

  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    privileged: true
    hostname: "blackbox"
    restart: always
    networks:
    - website_monitoring
    ports:  
    - "127.0.0.1:9115:9115"
    user: root
    volumes:
    - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
    - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  grafana:
    image: "grafana/grafana:latest"
    hostname: "grafana"
    restart: always
    networks:
    - website_monitoring
    ports:
    - "127.0.0.1:3000:3000"
    environment:
    # - "GF_SECURITY_ADMIN_PASSWORD=ITSCOOL"
    - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes:
    - "./config/grafana/provisioning:/etc/grafana/provisioning"

  alertmanager:
    image: "prom/alertmanager:latest"
    restart: unless-stopped
    networks:
    - website_monitoring
    ports:
      - "127.0.0.1:9093:9093"
    privileged: true  
    user: root
    volumes:
      - "./config/alertmanager/alertmanager.yml:/etc/prometheus/alertmanager.yml:ro"
      - alertmanager-data:/data
    command: 
      - "--config.file=/etc/prometheus/alertmanager.yml"
    

volumes:
  prometheus_data:
  alertmanager-data:

networks:
  website_monitoring:

